# .github/workflows/update-html-title.yml
name: Update HTML Title

# Trigger the workflow manually using `workflow_dispatch`
on:
  workflow_dispatch:
    inputs:
      newTitle:
        description: "The new title for the HTML page"
        required: true
        default: "My Updated Project Title"

jobs:
  update-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update title in index.html
        run: |
          # Define the input title
          newTitle="${{ github.event.inputs.newTitle }}"

          # Use sed to replace the title in index.html
          sed -i 's|<title>.*</title>|<title>'"$newTitle"'</title>|' docs/index.html

          # Verify the change
          echo "Updated title to: $newTitle"
          cat docs/index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Update HTML title to: $newTitle"
          git push
